
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package org.test;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630396
 * 2020-09-18T10:38:43.242+05:30
 * Generated source version: 3.1.5.redhat-630396
 * 
 */

@javax.jws.WebService(
                      serviceName = "TestRequest",
                      portName = "TestRequestSoap12",
                      targetNamespace = "http://test.org/",
                      wsdlLocation = "file:/home/avinash/IdeaProjects/cxf-cf/src/main/resources/wsdl/TestRequestSoap.wsdl",
                      endpointInterface = "org.test.TestRequestSoap")
                      
public class TestRequestSoap12Impl implements TestRequestSoap {

    private static final Logger LOG = Logger.getLogger(TestRequestSoap12Impl.class.getName());

    /* (non-Javadoc)
     * @see org.test.TestRequestSoap#sampleRequest(int  number1 ,)java.lang.String  string2 ,)java.lang.String  string3 ,)java.lang.Boolean  sampleRequestResult )*
     */
    public void sampleRequest(int number1,java.lang.String string2,javax.xml.ws.Holder<java.lang.String> string3,javax.xml.ws.Holder<java.lang.Boolean> sampleRequestResult) { 
        LOG.info("Executing operation sampleRequest");
        System.out.println(number1);
        System.out.println(string2);
        System.out.println(string3.value);
        try {
            java.lang.Boolean sampleRequestResultValue = null;
            sampleRequestResult.value = sampleRequestResultValue;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
