package org.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630396
 * 2020-09-18T10:38:43.251+05:30
 * Generated source version: 3.1.5.redhat-630396
 * 
 */
@WebServiceClient(name = "TestRequest", 
                  wsdlLocation = "file:/home/avinash/IdeaProjects/cxf-cf/src/main/resources/wsdl/TestRequestSoap.wsdl",
                  targetNamespace = "http://test.org/") 
public class TestRequest extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://test.org/", "TestRequest");
    public final static QName TestRequestSoap = new QName("http://test.org/", "TestRequestSoap");
    public final static QName TestRequestSoap12 = new QName("http://test.org/", "TestRequestSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/avinash/IdeaProjects/cxf-cf/src/main/resources/wsdl/TestRequestSoap.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestRequest.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/avinash/IdeaProjects/cxf-cf/src/main/resources/wsdl/TestRequestSoap.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestRequest(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestRequest(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestRequest() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public TestRequest(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestRequest(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestRequest(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap")
    public TestRequestSoap getTestRequestSoap() {
        return super.getPort(TestRequestSoap, TestRequestSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap")
    public TestRequestSoap getTestRequestSoap(WebServiceFeature... features) {
        return super.getPort(TestRequestSoap, TestRequestSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap12")
    public TestRequestSoap getTestRequestSoap12() {
        return super.getPort(TestRequestSoap12, TestRequestSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestRequestSoap
     */
    @WebEndpoint(name = "TestRequestSoap12")
    public TestRequestSoap getTestRequestSoap12(WebServiceFeature... features) {
        return super.getPort(TestRequestSoap12, TestRequestSoap.class, features);
    }

}
